/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalpage;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import library.issuebk;
import library.returnbk;

/**
 *
 * @author User
 */
public class ciculation extends javax.swing.JInternalFrame {

    /**
     * Creates new form ciculation
     */
    public ciculation() {
        initComponents();
           initComponents(); this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BORROWBOOK = new javax.swing.JLabel();
        borrowbook = new javax.swing.JButton();
        returnbook = new javax.swing.JButton();
        RETURNBOOK = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BORROWBOOK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BORROWBOOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/book (4).png"))); // NOI18N
        BORROWBOOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BORROWBOOKMouseClicked(evt);
            }
        });
        jPanel1.add(BORROWBOOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 130, 140));

        borrowbook.setText("ISSUE BOOK");
        borrowbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowbookActionPerformed(evt);
            }
        });
        jPanel1.add(borrowbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 130, 30));

        returnbook.setText("RETURN BOOK");
        returnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbookActionPerformed(evt);
            }
        });
        jPanel1.add(returnbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 130, 30));

        RETURNBOOK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RETURNBOOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/return (2).png"))); // NOI18N
        RETURNBOOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RETURNBOOKMouseClicked(evt);
            }
        });
        jPanel1.add(RETURNBOOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 130, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/managing-remote-employees-630x450-c.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbookActionPerformed
         returnbk rbk = new returnbk();
        rbk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnbookActionPerformed

    private void BORROWBOOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BORROWBOOKMouseClicked
        issuebk ibk = new issuebk();
        ibk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BORROWBOOKMouseClicked

    private void borrowbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowbookActionPerformed
         issuebk ibk = new issuebk();
        ibk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_borrowbookActionPerformed

    private void RETURNBOOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RETURNBOOKMouseClicked
        returnbk rbk = new returnbk();
        rbk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RETURNBOOKMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BORROWBOOK;
    private javax.swing.JLabel RETURNBOOK;
    private javax.swing.JButton borrowbook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton returnbook;
    // End of variables declaration//GEN-END:variables
}
