/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalpage;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import library.addbook;
import library.addstudent;

/**
 *
 * @author User
 */
public class manage extends javax.swing.JInternalFrame {

    /**
     * Creates new form manage
     */
    public manage() {
        initComponents();
           initComponents(); this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ADDSTUDENT = new javax.swing.JButton();
        ADDBOOK = new javax.swing.JButton();
        addstudent = new javax.swing.JLabel();
        addbook = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ADDSTUDENT.setText("ADD STUDENT");
        ADDSTUDENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDSTUDENTActionPerformed(evt);
            }
        });
        jPanel1.add(ADDSTUDENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 140, 40));

        ADDBOOK.setText("ADD BOOK");
        ADDBOOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDBOOKMouseClicked(evt);
            }
        });
        jPanel1.add(ADDBOOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 140, 40));

        addstudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addstudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/contact.png"))); // NOI18N
        addstudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addstudentMouseClicked(evt);
            }
        });
        jPanel1.add(addstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 140, 160));

        addbook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        addbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbookMouseClicked(evt);
            }
        });
        jPanel1.add(addbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 140, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/managing-remote-employees-630x450-c.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ADDSTUDENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDSTUDENTActionPerformed
        addstudent as = new addstudent();
      as.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_ADDSTUDENTActionPerformed

    private void addbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbookMouseClicked
      addbook ak = new addbook();
      ak.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_addbookMouseClicked

    private void ADDBOOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDBOOKMouseClicked
       addbook ak = new addbook();
      ak.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_ADDBOOKMouseClicked

    private void addstudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addstudentMouseClicked
         addstudent as = new addstudent();
      as.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_addstudentMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDBOOK;
    private javax.swing.JButton ADDSTUDENT;
    private javax.swing.JLabel addbook;
    private javax.swing.JLabel addstudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
